added docker build

diff --git a/.github/workflows/continuous-integration-workflow.yml b/.github/workflows/continuous-integration-workflow.yml
--- a/.github/workflows/continuous-integration-workflow.yml
+++ b/.github/workflows/continuous-integration-workflow.yml
@@ -15,13 +15,13 @@ jobs:
     - uses: actions/checkout@v2 # Adds a step to checkout the repository code
 
     - name: DotNet Build
-      id: s0001
+      # id: s0001
       run: dotnet build
-      continue-on-error: true
+      # continue-on-error: true
 
-    - name: Check for DotNet build failure
-      if: steps.s0001.outcome != 'success'
-      run: echo "Detected a failure" && exit 1
+    # - name: Check for DotNet build failure
+    #   if: steps.s0001.outcome != 'success'
+    #   run: echo "Detected a failure" && exit 1
 
     - name: Dotnet test
       run: dotnet test
@@ -35,10 +35,22 @@ jobs:
     - name: npm tests
       run: cd DotnetTemplate.Web && npm run test
 
-    - name: TEST GitHub Action trigger data to Slack workflow
-      id: slack
-      uses: slackapi/slack-github-action@v1.14.0
-      with:
-        payload: "{\"text\":\"GitHub -> This is a test from Tarne\"}"
-      env:
-        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+    # - name: TEST GitHub Action trigger data to Slack workflow
+    #   id: slack
+    #   uses: slackapi/slack-github-action@v1.14.0
+    #   with:
+    #     payload: "{\"text\":\"GitHub -> This is a test from Tarne\"}"
+    #   env:
+    #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
+      
+    - name: Docker build
+      id: docker_build
+      run: docker build -f Dockerfile.Module-08 --tag tarne75/dotnettemplate:workflow .
+
+    - name: Docker login
+      id: docker_login
+      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
+    
+    - name: Docker push
+      id: docker_push
+      run: docker push tarne75/dotnettemplate:workflow
